# -*- coding: utf-8 -*-
"""Calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iCcpdZD_HTchDjfBSlcUsqViBJxd-3fw
"""

print ("Para soma digite:          1")
print ("Para divisão digite:       2")
print ("Para multiplicação digite: 3")
print ("Para subtração digite:     4")

Operacao = input('Digite a operação desejada entre dois números inteiros:')

valor1 = int(input("Digite o primeiro valor: "))
valor2 = int(input("Digite o segundo valor: "))

if Operacao == "1":
  print ('O resultado é:',(valor1 + valor2))
elif Operacao == "2":
  print ('O resultado é:', (valor1 / valor2))
elif Operacao == "3":
  print ('O resultado é:', (valor1 * valor2))
elif Operacao == "4":
  print ('O resultado é:', (valor1 - valor2))